<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.example.reddit</groupId>
    <artifactId>reddit-app</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>usecase</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.example.reddit</groupId>
      <artifactId>domain</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>

